### ISSUE TITLE
BigTable instance resource corruption on update- hashed attribute names duplicated

### ISSUE THREAD

**Issue by EmilyMazo** [terraform-providers/terraform-provider-google#2582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.10

### Affected Resource(s)

google_bigtable_instance

* google_XXXXX

### Terraform Configuration Files

```tf
resource "google_bigtable_instance" "emazo-instance" {
  name = "emazo-az-server"

  cluster {
    cluster_id   = "emazo-az-server-cluster"
    zone         = "us-central1-c"
    num_nodes    = 24
    storage_type = "SSD"
  }
}
```

### Debug Output
Observed results when running plan and apply:
https://gist.github.com/EmilyMazo/922a0dcffe911e597e34eeaa832adb7b

Further error messages after pulling the configuration file repository and running `terraform plan` again: https://gist.github.com/EmilyMazo/a79e71b6b8e73bb6ca4ae145eb8b2c20

### Panic Output

None
### Expected Behavior

We expected a terraform plan to update the attributes of the bigtable.instance resource. 

### Actual Behavior

The resource apply shows unexpected output that changes the name of attributes (with hashes) and includes duplicates:
```
google_bigtable_instance.emazo-instance: Modifying... (ID: emazo-az-server)
  cluster.1049511826.cluster_id:   "emazo-az-server-cluster" => ""
  cluster.1049511826.num_nodes:    "12" => "0"
  cluster.1049511826.storage_type: "SSD" => ""
  cluster.1049511826.zone:         "us-central1-c" => "us-central1-c"
  cluster.1992645543.cluster_id:   "" => "emazo-az-server-cluster"
  cluster.1992645543.num_nodes:    "" => "24"
  cluster.1992645543.storage_type: "" => "SSD"
  cluster.1992645543.zone:         "" => "us-central1-c"
google_bigtable_instance.emazo-instance: Modifications complete after 0s (ID: emazo-az-server)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Afterwards, the state file appears corrupted- the duplicated attribute names for each resource may have led to cluster ID not being found. 
```
* google_bigtable_instance.emazo-instance: google_bigtable_instance.emazo-instance: Error retrieving cluster "": rpc error: code = InvalidArgument desc = When parsing 'projects/etsy-aznext-sandbox/instances/emazo-az-server/clusters/' : Cluster name expected in the form 'projects/<project_id>/instances/<instance_id>/clusters/<cluster_id>'.
```

### Steps to Reproduce

1. Create a bigtable.instance resource of any size.
2. `terraform apply`
3. Change the resource in some way.
4. `terraform apply`

### References

Another user saw the same issue on 11/02/2018 https://github.com/terraform-providers/terraform-provider-google/issues/2400

And there are two other issues in other resources that appear to reproduce this problem in CloudSQL and DataProc resources:
https://github.com/terraform-providers/terraform-provider-google/issues/2554
https://github.com/terraform-providers/terraform-provider-google/issues/2565

* #0000

**Comment by EmilyMazo** [comment]
Hi @rileykarson, do you know when this fix might go out in a release?

**Comment by rileykarson** [comment]
Hey @EmilyMazo!

The fix I sent will work from `2.0.0` onwards, but won't work in `1.X.X` releases unfortunately. `2.0.0` will release roughly alongside Terraform `0.12`.

I couldn't find a solution for it in `1.X.X` - I would suggest manually destroying the resource to apply the changes as a workaround in the meantime, as `Create` should work correctly. I've sent details of the issues I encountered to another developer, and they'll hopefully be able to identify a fix.

**Comment by inge4pres** [comment]
Just a help for you @EmilyMazo 
the creation/modification/destroy lifecycle works perfectly with 0.11.x if you use the deprecated options like

```
resource "google_bigtable_instance" "instance" {
  name = "my-dev-instance"
  cluster_id = "dev"
  instance_type = "DEVELOPMENT"
  zone = "europe-west1-c"
  num_nodes = 1
  storage_type = "SSD"
}
```
Hope this helps

**Comment by EmilyMazo** [comment]
Hi @inge4pres! I may be missing something, but I don't think that's true as far as changing `num_nodes` is concerned- 

```

-/+ google_bigtable_instance.bigtable-us-central1-a-test (new resource required)
      id:            "bigtable-us-central1-a-test" => <computed> (forces new resource)
      cluster_id:    "test-cluster" => "test-cluster"
      display_name:  "bigtable-us-central1-a-test" => <computed>
      instance_type: "PRODUCTION" => "PRODUCTION"
      name:          "bigtable-us-central1-a-test" => "bigtable-us-central1-a-test"
      num_nodes:     "3" => "6" (forces new resource)
      project:       "aznext-sandbox" => <computed>
      storage_type:  "SSD" => "SSD"
      zone:          "us-central1-a" => "us-central1-a"


Plan: 1 to add, 0 to change, 1 to destroy.

```

It appears on testing manually (in Terraform v0.11.10 + provider.google v1.20.0) that modification of this parameter leads to forced destruction of the resource. For our use case, this means that we cannot use terraform for this resource in a production environment.

**Comment by galic1987** [comment]
Any update on this? 

I tried the quick fix but it does not work for me... 
Terraform v0.11.11
+ provider.google v1.20.0

* google_bigtable_instance.instance: google_bigtable_instance.instance: Error retrieving cluster "": rpc error: code = InvalidArgument desc = When parsing 'projects/xxx-terraform-commander/instances/cr-bigtable/clusters/' : Cluster name expected in the form 'projects/<project_id>/instances/<instance_id>/clusters/<cluster_id>'.



> Just a help for you @EmilyMazo
> the creation/modification/destroy lifecycle works perfectly with 0.11.x if you use the deprecated options like
> 
> ```
> resource "google_bigtable_instance" "instance" {
>   name = "my-dev-instance"
>   cluster_id = "dev"
>   instance_type = "DEVELOPMENT"
>   zone = "europe-west1-c"
>   num_nodes = 1
>   storage_type = "SSD"
> }
> ```
> Hope this helps

**Comment by rileykarson** [comment]
This should be resolved in `2.0.0`. If you're using the deprecated field, you can go to version `1.20.0`, upgrade to the new field, and then upgrade to `2.0.0`.

Sorry for the pain point here! Unfortunately, this migration was necessary in order to support cluster replication.

**Comment by EmilyMazo** [comment]
Hi @rileykarson! We have upgraded to ~2.0.0 and we are still seeing the original activity when trying to change a Bigtable resource. 

Original tf config:
```
resource "google_bigtable_instance" "bigtable" {
  count = 1

  name = "bigtable-banana"

  cluster {
    cluster_id   = "bigtable-banana"
    zone         = "us-central1-a"
    num_nodes    = 10
    storage_type = "SSD"
  }

  cluster {
    cluster_id   = "bigtable-banana-c2"
    zone         = "us-central1-a"
    num_nodes    = 10
    storage_type = "SSD"
  }
}
```
Output of `terraform apply` (truncated):
```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

New/updated tf config (scaling the size of one cluster from 10 to 15 nodes):
```
resource "google_bigtable_instance" "bigtable" {
  count = 1

  name = "bigtable-banana"

  cluster {
    cluster_id   = "bigtable-banana"
    zone         = "us-central1-a"
    num_nodes    = 15
    storage_type = "SSD"
  }

  cluster {
    cluster_id   = "bigtable-banana-c2"
    zone         = "us-central1-a"
    num_nodes    = 10
    storage_type = "SSD"
  }
}
```

Output of `terraform plan`:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ google_bigtable_instance.bigtable (new resource required)
      id:                              "bigtable-banana" => <computed> (forces new resource)
      cluster.#:                       "2" => "2"
      cluster.3493891827.cluster_id:   "bigtable-banana-c2" => "bigtable-banana-c2"
      cluster.3493891827.num_nodes:    "10" => "10"
      cluster.3493891827.storage_type: "SSD" => "SSD"
      cluster.3493891827.zone:         "us-central1-a" => "us-central1-a"
      cluster.4185613649.cluster_id:   "" => "bigtable-banana" (forces new resource)
      cluster.4185613649.num_nodes:    "" => "15" (forces new resource)
      cluster.4185613649.storage_type: "" => "SSD" (forces new resource)
      cluster.4185613649.zone:         "" => "us-central1-a" (forces new resource)
      cluster.792946168.cluster_id:    "bigtable-banana" => "" (forces new resource)
      cluster.792946168.num_nodes:     "10" => "0" (forces new resource)
      cluster.792946168.storage_type:  "SSD" => "" (forces new resource)
      cluster.792946168.zone:          "us-central1-a" => "" (forces new resource)
      cluster_id:                      "" => <computed>
      display_name:                    "bigtable-banana" => <computed>
      instance_type:                   "PRODUCTION" => "PRODUCTION"
      name:                            "bigtable-banana" => "bigtable-banana"
      num_nodes:                       "" => <computed>
      project:                         "aznext-sandbox" => <computed>
      storage_type:                    "" => <computed>
      zone:                            "" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by rileykarson** [comment]
Ah, my apologies. https://github.com/GoogleCloudPlatform/magic-modules/pull/993 fixed the problem where Terraform was unable to perform an update; this message in the original issue:

```
* google_bigtable_instance.emazo-instance: google_bigtable_instance.emazo-instance: Error retrieving cluster "": rpc error: code = InvalidArgument desc = When parsing 'projects/etsy-aznext-sandbox/instances/emazo-az-server/clusters/' : Cluster name expected in the form 'projects/<project_id>/instances/<instance_id>/clusters/<cluster_id>'.
```

The provider still doesn't support updating the cluster(s), but properly supports recreating the instance when clusters have changed. https://github.com/terraform-providers/terraform-provider-google/issues/2521 tracks support for updating clusters, so I'll post an update there.
