### ISSUE TITLE
google_compute_region_instance_group_manager: Error: insufficient items for attribute "version"; must have at least 1

### ISSUE THREAD

**Issue by BenCoughlan15** [terraform-providers/terraform-provider-google#4459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.8
+ provider.google v2.14.0
+ provider.google-beta v2.14.0

### Affected Resource(s)

google_compute_region_instance_group_manager

### Terraform Configuration Files

https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html

```tf
terraform state rm module.instance_group_manager_uk-app-v1.google_compute_region_instance_group_manager.appserver

terraform import -provider=google-beta module.instance_group_manager_uk-app-v1.google_compute_region_instance_group_manager.appserver  test-project-name/europe-west2/uk-app-v1

terraform state rm module.instance_group_manager_us-app-v1.google_compute_region_instance_group_manager.appserver
terraform import -provider=google-beta module.instance_group_manager_us-app-v1.google_compute_region_instance_group_manager.appserver  test-project-name/europe-west2/us-app-v1

```

### Debug Output

https://gist.github.com/chrisbenincasa/645252d3546c4a8609e8189629fc8e11

### Expected Behavior

Terraform should apply and create resources. 

### Actual Behavior

```Error: insufficient items for attribute "version"; must have at least 1```

### Workaround for error. 

```tf
terraform state rm module.instance_group_manager_uk-app-v1.google_compute_region_instance_group_manager.appserver

terraform import -provider=google-beta module.instance_group_manager_uk-app-v1.google_compute_region_instance_group_manager.appserver  test-project-name/europe-west2/uk-app-v1

terraform state rm module.instance_group_manager_us-app-v1.google_compute_region_instance_group_manager.appserver
terraform import -provider=google-beta module.instance_group_manager_us-app-v1.google_compute_region_instance_group_manager.appserver  test-project-name/europe-west2/us-app-v1

terraform apply
```
^^ This will succeed. 

Also, the documentation here is poor : https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html
it says: 
```terraform import google_compute_region_instance_group_manager.appserver appserver-igm``` 

It should say something like: 

```
terraform import -provider=google-beta module.instance_group_manager_us-app-v1.google_compute_region_instance_group_manager.appserver  <test-priject-id>/<region>/<Instance_group_id>
```

1. `terraform apply`

### Important Factoids

none

### References

https://www.gitmemory.com/issue/terraform-providers/terraform-provider-google/4169/520044805

**Comment by rileykarson** [comment]
Based on your debug logs, it looks like you're using Terraform `0.12.6` and not `0.12.8`. This is an occurrence of https://github.com/hashicorp/terraform/issues/22387, and is resolved in `0.12.7`.

Closing this out- if you upgrade your Terraform version and this continues to fail, please comment with an updated debug log!

**Comment by BenCoughlan15** [comment]
hi there, 

I'm using Terraform v0.12.8, this issue still exists, I've just referenced another issue with the same behaviour.

**Comment by rileykarson** [comment]
Ah- the debug logs were pulled from there, got it. Based on https://github.com/hashicorp/terraform/issues/22387 we expect this to be resolved in `0.12.8`, so are you able to attach new debug logs here / upstream on that issue?

**Comment by rileykarson** [comment]
Closing as stale.
