### ISSUE TITLE
Terraform Crashes while creating VM within VPC in Google Cloud

### ISSUE THREAD

**Issue by naoleyrashmi** [terraform-providers/terraform-provider-google#586]
Terraform Version

v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance
-google_compute_network

### Terraform Configuration Files

resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "n1-standard-1"
  zone         = "us-east1-c"

  tags = ["test1", "vm"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-8"
    }
  }

  network_interface {
    network = "${var.testvpc_id}"

    access_config {
      // Ephemeral IP
    }
  }
}

Few Pointers:
* Please note that this scenario is only replicable when a VPC is created in some other module and referenced as a variable which is already set in variables.tf
* When an instance and  VPC are created within same module this issue is not faced.
### Crash Output
[crash.log](https://github.com/terraform-providers/terraform-provider-google/files/1386437/crash.log)
[crash.log](https://github.com/terraform-providers/terraform-provider-google/files/1386448/crash.log)

Expected Behavior

A VM to be created within VPC 

Actual Behavior

Terraform crashed

Steps to Reproduce

    terraform init
    terraform apply

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-556 
- GH-585

**Comment by danawillow** [comment]
Hey @naoleyrashmi, are you creating the VPC in the other module at the time of the crash or has it already been created? Without actually looking at the logs, I wonder whether the instance is trying to be created when the network hasn't been finished creating since you're referring to it by variable name rather than interpolation.

**Comment by naoleyrashmi** [comment]
hello @danawillow VPC has already been created in some other module and then passing the value of network in current module via variable. Moreover its worth noticing that when an instance and VPC are created within same module this issue is not faced.

**Comment by zopanix** [comment]
Hey,
@danawillow, I'm having the same issues here since today. (I didn't test during the week end) on some disks. It created some of the stuff but not everything.

Terraform Version: 0.10.7
Google Provider Version: 1.0.0


I use terraform to spin up environments at will, versions of this setup have worked before, the only thing that changes are the disk images reference.
```
Error applying plan:

10 error(s) occurred:

* google_compute_disk.madmst: 1 error(s) occurred:

* google_compute_disk.madmst: unexpected EOF
* google_compute_disk.madslv: 1 error(s) occurred:

* google_compute_disk.madslv: unexpected EOF
* google_compute_disk.gfsmst-1: 1 error(s) occurred:

* google_compute_disk.gfsmst-1: unexpected EOF
* google_compute_instance.pdbslv: 1 error(s) occurred:

* google_compute_instance.pdbslv: unexpected EOF
* google_compute_disk.gfsslv-0: 1 error(s) occurred:

* google_compute_disk.gfsslv-0: unexpected EOF
* google_compute_disk.madslv-data: 1 error(s) occurred:

* google_compute_disk.madslv-data: unexpected EOF
* google_compute_disk.gfsslv-1: 1 error(s) occurred:

* google_compute_disk.gfsslv-1: unexpected EOF
* google_compute_forwarding_rule.fwd-rdpall-0: 1 error(s) occurred:

* google_compute_forwarding_rule.fwd-rdpall-0: unexpected EOF
* google_compute_disk.madmst-data: 1 error(s) occurred:

* google_compute_disk.madmst-data: unexpected EOF
* google_compute_instance.pdbmst: 1 error(s) occurred:

* google_compute_instance.pdbmst: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2017-10-23T14:21:09.045Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x140 pc=0x102cda4]
2017-10-23T14:21:09.045Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 
2017-10-23T14:21:09.046Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: goroutine 617 [running]:
2017-10-23T14:21:09.046Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/google.(*ComputeOperationWaiter).RefreshFunc.func1(0xc42003ff20, 0x1, 0x0, 0x0, 0xc4203b8d30, 0x43a56f)
2017-10-23T14:21:09.046Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/google/compute_operation.go:27 +0x64
2017-10-23T14:21:09.046Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc4204d4a20, 0xc42007b3b0, 0xc4204bc840, 0xc42020d7a0, 0xc420604f28, 0xc420604f20)
2017-10-23T14:21:09.046Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x4e0
2017-10-23T14:21:09.046Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: created by github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
2017-10-23T14:21:09.047Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1d0
2017-10-23T14:21:09.054Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: panic: interface conversion: interface {} is nil, not *compute.Operation
2017-10-23T14:21:09.054Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 
2017-10-23T14:21:09.054Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: goroutine 533 [running]:
2017-10-23T14:21:09.055Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/google.computeOperationWaitTime(0xc4204c2900, 0x0, 0xc42058e460, 0x17, 0x14241ac, 0x12, 0x4, 0xf180a0, 0xc4202a4e00)
2017-10-23T14:21:09.055Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/google/compute_operation.go:88 +0x332
2017-10-23T14:21:09.055Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/google.computeSharedOperationWaitTime(0xc4204c2900, 0x11ded60, 0x0, 0xc42058e460, 0x17, 0x4, 0x14241ac, 0x12, 0xc4205443f0, 0xc4204a1010)
2017-10-23T14:21:09.055Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/google/compute_shared_operation.go:19 +0xa3
2017-10-23T14:21:09.056Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/google.resourceComputeInstanceCreate(0xc4202a4e00, 0x11cec80, 0xc4204c2900, 0x24, 0x1c88d00)
2017-10-23T14:21:09.056Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/google/resource_compute_instance.go:793 +0x2a8b
2017-10-23T14:21:09.056Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420322660, 0xc4204dd590, 0xc420388c00, 0x11cec80, 0xc4204c2900, 0x1, 0xc4209d6300, 0xc4209d6300)
2017-10-23T14:21:09.056Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:193 +0x3b6
2017-10-23T14:21:09.056Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4207b6b60, 0xc4204dd540, 0xc4204dd590, 0xc420388c00, 0x7fdd454e86c8, 0x0, 0xc4207b6bd0)
2017-10-23T14:21:09.057Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0xa4
2017-10-23T14:21:09.057Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4204356c0, 0xc420388ba0, 0xc4205e8720, 0x0, 0x0)
2017-10-23T14:21:09.057Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017-10-23T14:21:09.057Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: reflect.Value.call(0xc4203228a0, 0xc420137860, 0x13, 0x1416543, 0x4, 0xc420597f20, 0x3, 0x3, 0x0, 0x0, ...)
2017-10-23T14:21:09.057Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x906
2017-10-23T14:21:09.058Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: reflect.Value.Call(0xc4203228a0, 0xc420137860, 0x13, 0xc4206c6720, 0x3, 0x3, 0xc4206a2090, 0x0, 0x0)
2017-10-23T14:21:09.058Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017-10-23T14:21:09.058Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: net/rpc.(*service).call(0xc420397940, 0xc4203be7d0, 0xc4206047d8, 0xc4204e4400, 0xc420435f20, 0x10d2580, 0xc420388ba0, 0x16, 0x10d25c0, 0xc4205e8720, ...)
2017-10-23T14:21:09.058Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2017-10-23T14:21:09.058Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: created by net/rpc.(*Server).ServeCodec
2017-10-23T14:21:09.058Z [DEBUG] plugin.terraform-provider-google_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.gfsslv-1: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.gfsslv-1: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.gfsslv-1
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_instance.gfsslv-1"
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_forwarding_rule.fwd-rdpall-0: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_forwarding_rule.fwd-rdpall-0: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_forwarding_rule.fwd-rdpall-0
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_instance.pdbslv: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_instance.pdbslv: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_instance.pdbslv
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.madslv: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.madslv: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.madslv
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.gfsslv-0: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.gfsslv-0: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.gfsslv-0
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_instance.gfsslv-0"
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.madslv-data: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.madslv-data: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.madslv-data
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_instance.madslv"
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_route.rte-madslv"
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "provider.google.backup (close)"
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_instance.pdbmst: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_instance.pdbmst: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_instance.pdbmst
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.madmst: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.madmst: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.madmst
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.madmst-data: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.madmst-data: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.madmst-data
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_instance.madmst"
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_route.rte-madmst"
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalIf
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteState
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/10/23 14:21:09 [TRACE] root: eval: *terraform.EvalApplyPost
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* google_compute_disk.gfsmst-1: unexpected EOF
2017/10/23 14:21:09 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* google_compute_disk.gfsmst-1: unexpected EOF
2017/10/23 14:21:09 [TRACE] [walkApply] Exiting eval tree: google_compute_disk.gfsmst-1
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "google_compute_instance.gfsmst-1"
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "provider.google (close)"
2017/10/23 14:21:09 [TRACE] dag/walk: upstream errored, not walking "root"
2017/10/23 14:21:09 [TRACE] Preserving existing state lineage "07ba12a6-0f49-4d70-9dce-a875e21c6ae5"
2017-10-23T14:21:09.080Z [DEBUG] plugin: plugin process exited: path=/data/.terraform/plugins/linux_amd64/terraform-provider-google_v1.0.0_x4
2017/10/23 14:21:09 [TRACE] Preserving existing state lineage "07ba12a6-0f49-4d70-9dce-a875e21c6ae5"
2017/10/23 14:21:09 [TRACE] Preserving existing state lineage "07ba12a6-0f49-4d70-9dce-a875e21c6ae5"
2017/10/23 14:21:09 [TRACE] Preserving existing state lineage "07ba12a6-0f49-4d70-9dce-a875e21c6ae5"
2017/10/23 14:21:09 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-10-23T14:21:09.133Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by danawillow** [comment]
I'm pretty sure you're both experiencing https://github.com/terraform-providers/terraform-provider-google/issues/553, which was fixed in v1.0.1 of the google provider. Try upgrading and let me know how it goes.

In the meantime, I'm going to close this issue (since I think it's a duplicate) but please do let me know if upgrading doesn't fix the problem.

**Comment by naoleyrashmi** [comment]
@danawillow  I did try upgrading but unfortunately it didn't work. Can you please suggest way forward to resolve this. Moreover it seems #553 is already closed , whereas i am still facing issue.

**Comment by danawillow** [comment]
@naoleyrashmi mind sending me another set of debug logs? That'll help me with line numbers and such.

**Comment by naoleyrashmi** [comment]
@danawillow  i am no more facing this issue. You might close this case. Thanks for your help.
